temp/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Class_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                    <default>true</default>
                    <label>Read</label>
                </value>
                <value>
                    <fullName>Edit</fullName>
                    <label>Read/Edit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Class Team Members</relationshipLabel>
        <relationshipName>Class_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Class_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class Team Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/ClassTeamMemberSharingRecalculation.cls
public class ClassTeamMemberSharingRecalculation implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id FROM Class__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Class__c> classes){
        //delete existing sharing records.
        List<Class__share> sharesToDelete = [SELECT Id FROM Class__share WHERE ParentId in :classes AND RowCause = :Schema.Class__share.rowCause.Class_Team__c];
        delete sharesToDelete;
        
        List<Class_Team_Member__c> teamMembers = [SELECT Id, Class__c, Team_Member__c, Access_Level__c FROM Class_Team_Member__c WHERE Class__c IN :classes];
        
        new ClassTeamMemberTriggerHandler().createShares(teamMembers);
    }    
    
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    } 
}